name: bedside_clock
description: "Orologio da comodino con radio internet, temi giorno/notte e protezione anti burn-in"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.0
  audio_session: ^0.1.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
