import{all,put,del,get,uid,clearStore}from'./db.js';import{sanitize,sanitizeFinalPrompt,replacements}from'./sanitizer.js';import{translate,tagify}from'./translator.js';import*as comfy from'./comfy.js';import{Director}from'./director.js';import{openManual,generateExternal}from'./providers.js';import{initSpeechInputs}from'./speech.js';import{encodeBackup,decodeBackup,downloadText,chooseDirectory,writeDirectory}from'./backup.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],LS={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const state={workflows:[],characters:[],archive:[],activeWorkflow:null,translated:{char:'',scene:'',neg:''},director:null,slots:{},poseBlob:null,mappingId:null,backupHandle:null,backupTimer:null};
const formats={auto:null,'1:1':[1024,1024,'square 1:1 format'],'16:9':[1344,768,'widescreen 16:9 format'],'9:16':[768,1344,'vertical 9:16 format'],'4:3':[1152,896,'landscape 4:3 format'],'3:4':[896,1152,'portrait 3:4 format'],'21:9':[1536,640,'ultrawide 21:9 format']};
const negativeBase='deformed hands, extra fingers, missing fingers, fused fingers, too many fingers, mutated hands, poorly drawn hands, malformed limbs, extra limbs, missing limbs, disfigured, bad anatomy, distorted body proportions, asymmetrical face, cross-eyed, extra heads, cloned face, long neck, cropped head, cropped forehead, cropped face, head cut off, head out of frame, top of head missing, blurry, low quality, worst quality, jpeg artifacts, watermark, signature, text, username';
const sliderDefs=[['identityStrength','Forza identità',80],['characterStrength','Forza corpo/costume',75],['poseStrength','Forza posa',70],['faceConsistency','Coerenza volto',80],['costumeConsistency','Coerenza costume',75],['creativeFreedom','Libertà scenario',70]];
init();
async function init(){bindTabs();updateStickyNavOffset();addEventListener('resize',updateStickyNavOffset);loadSettings();initSpeechInputs({languageSelect:$('#speechLanguage')});state.workflows=await all('workflows');state.characters=await all('characters');state.archive=await all('archive');state.activeWorkflow=state.workflows.find(w=>w.active)||null;renderProviders();renderWorkflows();renderCharacters();renderArchive();renderSliders();state.director=new Director($('#topCanvas'),$('#sideCanvas'),$('#zoomCanvas'),()=>{renderDirector();rebuildPrompt()});renderDirector();renderSlots();renderSavedScenes();bind();rebuildPrompt();previewSanitize()}
function updateStickyNavOffset(){const h=document.querySelector('header')?.offsetHeight||0;document.documentElement.style.setProperty('--header-height',h+'px')}
function bindTabs(){$$('#tabs button').forEach(b=>b.onclick=()=>{$$('#tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab))})}
function connection(){return{protocol:$('#protocol').value,host:$('#host').value.trim(),port:$('#port').value.trim(),authType:$('#authType').value,username:$('#username').value,secret:$('#secret').value}}
function loadSettings(){const speechLang=localStorage.getItem('pdSpeechLanguage')||'it-IT';if($('#speechLanguage'))$('#speechLanguage').value=speechLang;const c=LS.get('connection',{});['protocol','host','port','authType','username','secret'].forEach(k=>{if(c[k]!=null&&$('#'+k))$('#'+k).value=c[k]});$('#mode').value=LS.get('mode','local')}
function bind(){['protocol','host','port','authType','username','secret'].forEach(k=>$('#'+k).addEventListener('change',()=>LS.set('connection',connection())));$('#mode').onchange=()=>{LS.set('mode',$('#mode').value);renderSlots()};$('#testConnection').onclick=testConnection;$('#workflowFiles').onchange=importWorkflows;$('#addCharacter').onclick=addCharacter;$('#poseImage').onchange=e=>{state.poseBlob=e.target.files[0]||null;renderSummary();rebuildPrompt()};$('#translate').onclick=translateAll;$('#copyPrompt').onclick=()=>navigator.clipboard.writeText($('#positivePrompt').value);$('#copyOpenProvider').onclick=()=>openManual(activeProvider(),$('#positivePrompt').value);$('#generate').onclick=generate;$('#saveScene').onclick=saveScene;$('#loadScene').onclick=loadScene;$('#deleteScene').onclick=deleteScene;$('#chooseBackupFolder').onclick=selectBackupFolder;$('#backupNow').onclick=backupNow;$('#exportBackup').onclick=exportBackup;$('#importBackup').onchange=importBackup;$('#autoBackup').onchange=configureAutoBackup;$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#saveMapping').onclick=saveMapping;$('#applySanitizer').onclick=applySanitizerToInputs;$('#showDictionary').onclick=openDictionary;$('#closeDictionary').onclick=()=>$('#dictionaryModal').classList.remove('open');['characterText','sceneText','negativeExtra'].forEach(id=>$('#'+id).addEventListener('input',debounce(()=>{if($('#safeMode').checked)previewSanitize()},250)));['style','format','posePreset','lighting','composition','consistency','safeMode','transparentBackground','frames','fps'].forEach(id=>$('#'+id).addEventListener('change',()=>{duration();rebuildPrompt()}));$$('.quality').forEach(x=>x.onchange=rebuildPrompt)}
async function testConnection(){LS.set('connection',connection());$('#connectionInfo').textContent='Connessione in corso…';try{const j=await comfy.test(connection());$('#status').classList.add('ok');$('#status b').textContent='Connesso';$('#connectionInfo').textContent=JSON.stringify(j,null,2)}catch(e){$('#status').classList.remove('ok');$('#status b').textContent='Errore';$('#connectionInfo').textContent='Errore: '+e.message}}
function renderProviders(){const providers=[['gemini','Google Gemini','Supporta testo e immagine di riferimento'],['openai','OpenAI','Generazione ed editing con immagine di riferimento'],['leonardo','Leonardo.ai','Testo → immagine']];const saved=LS.get('providers',{}),active=LS.get('activeProvider','openai');$('#providerCards').innerHTML=providers.map(([id,n,d])=>`<div class="card"><label><input type="radio" name="provider" value="${id}" ${active===id?'checked':''}> <b>${n}</b></label><p>${d}</p><label>Chiave API<input type="password" data-key="${id}" value="${escapeHtml(saved[id]||'')}"></label></div>`).join('');$$('[name=provider]').forEach(r=>r.onchange=()=>LS.set('activeProvider',r.value));$$('[data-key]').forEach(i=>i.onchange=()=>{const p=LS.get('providers',{});p[i.dataset.key]=i.value;LS.set('providers',p)})}
const activeProvider=()=>LS.get('activeProvider','openai');
async function importWorkflows(e){for(const file of e.target.files){try{const graph=JSON.parse(await file.text()),err=comfy.validateWorkflow(graph);if(err)throw new Error(err);await put('workflows',{id:uid(),name:file.name.replace(/\.json$/i,''),graph,mapping:{positive:[],negative:[],seed:{nodeId:'',field:'seed'},resolution:{nodeId:'',widthField:'width',heightField:'height'},frames:{nodeId:'',field:'length'},fps:{nodeId:'',field:'frame_rate'},images:[]},active:false,createdAt:Date.now()})}catch(x){alert(file.name+': '+x.message)}}state.workflows=await all('workflows');renderWorkflows();e.target.value=''}
function renderWorkflows(){$('#workflowList').innerHTML=state.workflows.map(w=>`<div class="card ${w.active?'active':''}"><h3>${escapeHtml(w.name)}</h3><small>${Object.keys(w.graph).length} nodi</small><div class="card-actions"><button data-select-wf="${w.id}">Seleziona</button><button data-map-wf="${w.id}">Mappa nodi</button><button data-del-wf="${w.id}">Elimina</button></div></div>`).join('')||'<p>Nessun workflow caricato.</p>';$$('[data-select-wf]').forEach(b=>b.onclick=async()=>{for(const w of state.workflows){w.active=w.id===b.dataset.selectWf;await put('workflows',w)}state.activeWorkflow=state.workflows.find(w=>w.active);renderWorkflows();renderSlots()});$$('[data-map-wf]').forEach(b=>b.onclick=()=>openMapping(b.dataset.mapWf));$$('[data-del-wf]').forEach(b=>b.onclick=async()=>{if(confirm('Eliminare il workflow?')){await del('workflows',b.dataset.delWf);state.workflows=await all('workflows');if(state.activeWorkflow?.id===b.dataset.delWf)state.activeWorkflow=null;renderWorkflows();renderSlots()}})}
function openMapping(id){const w=state.workflows.find(x=>x.id===id);state.mappingId=id;const opts=Object.entries(w.graph).map(([id,n])=>`<option value="${id}">${id} — ${escapeHtml(n.class_type)}</option>`).join('');const row=(type,r={})=>`<div class="mapping-row" data-type="${type}"><select class="node"><option value="">Nodo…</option>${opts}</select><input class="field" placeholder="Campo" value="${escapeHtml(r.field||'')}">${type==='images'?`<select class="source"><option value="character">Corpo/costume</option><option value="identity">Identità/volto</option><option value="pose">Posa</option></select><input class="label" placeholder="Etichetta" value="${escapeHtml(r.label||'')}">`:''}<button class="remove">×</button></div>`;const list=(title,type,arr)=>`<h3>${title}</h3><div id="map-${type}">${arr.map(r=>row(type,r)).join('')}</div><button data-add="${type}">+ Aggiungi</button>`;const m=w.mapping||{};$('#mappingEditor').innerHTML=list('Prompt positivi','positive',m.positive||[])+list('Prompt negativi','negative',m.negative||[])+singleMap('Seed','seed',m.seed,opts,['field'])+singleMap('Risoluzione','resolution',m.resolution,opts,['widthField','heightField'])+singleMap('Numero frame','frames',m.frames,opts,['field'])+singleMap('FPS','fps',m.fps,opts,['field'])+list('Immagini di riferimento','images',m.images||[]);$$('[data-add]').forEach(b=>b.onclick=()=>{$('#map-'+b.dataset.add).insertAdjacentHTML('beforeend',row(b.dataset.add));wireMapRows()});wireMapRows();Object.entries(m).forEach(([type,val])=>{if(Array.isArray(val))val.forEach((r,i)=>{const el=$$(`#map-${type} .mapping-row`)[i];if(el){el.querySelector('.node').value=r.nodeId||'';if(el.querySelector('.source'))el.querySelector('.source').value=r.source||'character'}});else{const box=$(`[data-single="${type}"]`);if(box){box.querySelector('.node').value=val?.nodeId||''}}});$('#modal').classList.add('open')}
function singleMap(title,type,val={},opts,fields){return`<h3>${title}</h3><div class="mapping-row" data-single="${type}"><select class="node"><option value="">Nodo…</option>${opts}</select>${fields.map(f=>`<input data-field="${f}" placeholder="${f}" value="${escapeHtml(val?.[f]||'')}">`).join('')}</div>`}
function wireMapRows(){$$('#mappingEditor .remove').forEach(b=>b.onclick=()=>b.parentElement.remove())}
async function saveMapping(){const w=state.workflows.find(x=>x.id===state.mappingId),m={};for(const type of['positive','negative','images'])m[type]=$$(`#map-${type} .mapping-row`).map(el=>({nodeId:el.querySelector('.node').value,field:el.querySelector('.field').value,...(type==='images'?{source:el.querySelector('.source').value,label:el.querySelector('.label').value}:{})})).filter(x=>x.nodeId&&x.field);for(const type of['seed','resolution','frames','fps']){const el=$(`[data-single="${type}"]`);m[type]={nodeId:el.querySelector('.node').value};el.querySelectorAll('[data-field]').forEach(i=>m[type][i.dataset.field]=i.value)}w.mapping=m;await put('workflows',w);state.workflows=await all('workflows');state.activeWorkflow=state.workflows.find(x=>x.active)||state.activeWorkflow;$('#modal').classList.remove('open');renderSlots();alert('Mappatura salvata.')}
async function addCharacter(){const name=$('#characterName').value.trim(),character=$('#characterImage').files[0],identity=$('#identityImage').files[0];if(!name||!character)return alert('Inserisci nome e immagine corpo/costume.');await put('characters',{id:uid(),name,character,identity:identity||null,hidden:false,createdAt:Date.now()});state.characters=await all('characters');$('#characterName').value='';$('#characterImage').value='';$('#identityImage').value='';renderCharacters();renderSlots()}
function blobUrl(b){return b?URL.createObjectURL(b):''}function renderCharacters(){$('#characterList').innerHTML=state.characters.map(c=>`<div class="card"><img class="thumb ${c.hidden?'blur':''}" src="${blobUrl(c.character)}"><input data-char-name="${c.id}" value="${escapeHtml(c.name)}"><small>Identità: ${c.identity?'presente':'non caricata'}</small><div class="card-actions"><button data-copy-char="${c.id}">Copia</button><button data-down-char="${c.id}">Scarica</button><button data-hide-char="${c.id}">👁️</button><label>Identità<input data-id-char="${c.id}" type="file" accept="image/*"></label><button data-del-char="${c.id}">Elimina</button></div></div>`).join('')||'<p>Nessun personaggio.</p>';$$('[data-char-name]').forEach(i=>i.onchange=async()=>{const c=state.characters.find(x=>x.id===i.dataset.charName);c.name=i.value;await put('characters',c);renderSlots()});$$('[data-copy-char]').forEach(b=>b.onclick=async()=>copyImage((state.characters.find(x=>x.id===b.dataset.copyChar)).character));$$('[data-down-char]').forEach(b=>b.onclick=()=>{const c=state.characters.find(x=>x.id===b.dataset.downChar);download(c.character,comfy.safeName(c.name)+'.png')});$$('[data-hide-char]').forEach(b=>b.onclick=async()=>{const c=state.characters.find(x=>x.id===b.dataset.hideChar);c.hidden=!c.hidden;await put('characters',c);renderCharacters()});$$('[data-id-char]').forEach(i=>i.onchange=async()=>{const c=state.characters.find(x=>x.id===i.dataset.idChar);c.identity=i.files[0]||null;await put('characters',c);renderCharacters();renderSlots()});$$('[data-del-char]').forEach(b=>b.onclick=async()=>{if(confirm('Eliminare?')){await del('characters',b.dataset.delChar);state.characters=await all('characters');renderCharacters();renderSlots()}})}
function renderSlots(){const maps=$('#mode').value==='local'?(state.activeWorkflow?.mapping?.images||[]):[];const relevant=maps.filter(x=>x.source!=='pose');const slots=relevant.length?relevant:[{nodeId:'external',field:'image',source:'character',label:'Personaggio di riferimento'}];$('#referenceSlots').innerHTML='<h3>Riferimenti personaggio</h3>'+slots.map((s,i)=>`<label>${escapeHtml(s.label||s.source)} — ${s.source==='identity'?'Identità (volto)':'Corpo/costume'}<select data-slot="${i}"><option value="">Non impostato</option>${state.characters.map(c=>`<option value="${c.id}" ${state.slots[i]===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label>`).join('')+(maps.filter(x=>x.source==='pose').length?'<p>Gli slot posa usano il file “Riferimento posa opzionale”.</p>':'');$$('[data-slot]').forEach(s=>s.onchange=()=>{state.slots[s.dataset.slot]=s.value;renderSummary();rebuildPrompt()});renderSummary()}
function selectedSources(){const maps=$('#mode').value==='local'?(state.activeWorkflow?.mapping?.images||[]):[];const relevant=maps.filter(x=>x.source!=='pose');const slots=relevant.length?relevant:[{nodeId:'external',field:'image',source:'character',label:'Personaggio'}];return slots.map((m,i)=>({map:m,char:state.characters.find(c=>c.id===state.slots[i])})).filter(x=>x.char)}
function renderSummary(){const maps=state.activeWorkflow?.mapping?.images||[],lines=[];maps.forEach((m,i)=>{if(m.source==='pose')lines.push(`posa → nodo ${m.nodeId}.${m.field} → ${state.poseBlob?'pose-reference.png':'non impostata'}`);else{const rel=maps.filter(x=>x.source!=='pose'),idx=rel.indexOf(m),c=state.characters.find(x=>x.id===state.slots[idx]);const exists=m.source==='identity'?c?.identity:c?.character;lines.push(`${m.source} → nodo ${m.nodeId}.${m.field} → ${exists?fileName(m.source,c):'non impostata'}`)}});$('#referenceSummary').textContent=lines.length?lines.join('\n'):'Modalità esterna / nessuna immagine mappata.'}
function fileName(source,c){return`${source==='identity'?'identity':'char'}-${comfy.safeName(c.name)}-${c.id.replace(/-/g,'').slice(0,8)}.png`}
function renderSliders(){$('#sliders').innerHTML=sliderDefs.map(([id,n,v])=>`<div class="range-row"><span>${n}</span><input id="${id}" type="range" min="0" max="100" value="${v}"><output>${v}</output></div>`).join('');sliderDefs.forEach(([id])=>$('#'+id).oninput=e=>{e.target.nextElementSibling.value=e.target.value;rebuildPrompt()})}
function previewSanitize(){const a=sanitize($('#characterText').value),b=sanitize($('#sceneText').value),changes=[...a.changes,...b.changes];const combined=[a.out,b.out].filter(Boolean).join('\n\n');$('#sanitizedPreview').textContent=combined||'Scrivi una descrizione per vedere l’anteprima.';$('#replacementReport').textContent=changes.length?changes.map(x=>`${x.from} → ${x.to} (${x.count})`).join('\n'):'Nessuna sostituzione.'}
function applySanitizerToInputs(){if(!$('#safeMode').checked){alert('Attiva Safe Prompt Optimization.');return}const a=sanitize($('#characterText').value),b=sanitize($('#sceneText').value),n=sanitize($('#negativeExtra').value);$('#characterText').value=a.out;$('#sceneText').value=b.out;$('#negativeExtra').value=n.out;state.translated={char:'',scene:'',neg:''};previewSanitize();rebuildPrompt();$('#progress').textContent='Correzioni applicate al testo. Premi “Traduci e prepara prompt”.'}
function openDictionary(){const rows=Object.entries(replacements).sort((a,b)=>a[0].localeCompare(b[0],'it')).map(([from,to])=>`<div class="dictionary-row"><code>${escapeHtml(from)}</code><span>→</span><code>${escapeHtml(to)}</code></div>`).join('');$('#dictionaryList').innerHTML=rows;$('#dictionaryModal').classList.add('open')}
async function translateAll(){let ct=$('#characterText').value,st=$('#sceneText').value,nt=$('#negativeExtra').value;let preChanges=[];if($('#safeMode').checked){const a=sanitize(ct),b=sanitize(st);ct=a.out;st=b.out;preChanges=[...a.changes,...b.changes]}$('#progress').textContent='Traduzione in corso…';[state.translated.char,state.translated.scene,state.translated.neg]=await Promise.all([translate(ct),translate(st),translate(nt)]);if($('#safeMode').checked){const a=sanitizeFinalPrompt(state.translated.char),b=sanitizeFinalPrompt(state.translated.scene);state.translated.char=a.out;state.translated.scene=b.out;const changes=[...preChanges,...a.changes,...b.changes];$('#replacementReport').textContent=changes.length?changes.map(x=>`${x.from} → ${x.to} (${x.count})`).join('\n'):'Nessuna sostituzione.'}rebuildPrompt();$('#progress').textContent='Prompt tradotto, controllato e preparato.'}
function weight(id){return(0.6+(Number($('#'+id).value)/100)*.9).toFixed(2)}
function consistencyBlock(){if(!$('#consistency').checked)return'';const src=selectedSources(),hasI=src.some(x=>x.map.source==='identity'&&x.char.identity),hasC=src.some(x=>x.map.source==='character'&&x.char.character),hasP=!!state.poseBlob,t=[];if(hasI)t.push(`(preserve the exact facial identity, face structure, eyes, hairstyle, hair color, apparent age and skin tone from the identity reference image:${weight('identityStrength')})`);if(hasC)t.push(`(preserve body proportions, costume, materials, symbols, accessories and color palette from the character reference image:${weight('characterStrength')})`);if(hasP)t.push(`(follow only the pose and composition of the pose reference, without copying its identity, face or clothing:${weight('poseStrength')})`);if(hasI)t.push(`(strong facial consistency across generations:${weight('faceConsistency')})`);if(hasC)t.push(`(strong costume and design consistency across generations:${weight('costumeConsistency')})`);t.push(`(scene, background, action, expression, framing and lighting may change creatively:${weight('creativeFreedom')})`);return t.join(', ')}
function rebuildPrompt(){const d=state.director?.state(),q=$$('.quality:checked').map(x=>x.value),fmt=formats[$('#format').value],parts=[tagify(state.translated.char,state.translated.scene),$('#style').value,d?.tags.join(', '),$('#lighting').value,$('#composition').value,q.join(', '),fmt?.[2],$('#posePreset').value,$('#transparentBackground').checked?'isolated character, transparent background, alpha channel, clean edges, PNG output, no scenery, no background':'' ,consistencyBlock(),'highly detailed, sharp focus, professional illustration, 4k'];let positive=tagify(...parts);if($('#safeMode').checked)positive=sanitizeFinalPrompt(positive).out;$('#positivePrompt').value=positive;$('#negativePrompt').value=tagify(negativeBase,state.translated.neg);renderDirector()}
function renderDirector(){const d=state.director?.state();if(d)$('#directorPreview').textContent=`Vista: ${d.view}\nAltezza: ${d.heightName}\nZoom: ${d.zoomName}\nLuce: ${$('#lighting').selectedOptions[0].text}\nComposizione: ${$('#composition').selectedOptions[0].text}`}
function duration(){const f=+$ ('#frames').value,p=+$ ('#fps').value;$('#duration').textContent=f&&p?`Durata: ${(f/p).toFixed(2)} secondi`:'Durata: —'}
async function generate(){try{$('#generate').disabled=true;if(!$('#positivePrompt').value.trim())await translateAll();if($('#safeMode').checked){const checked=sanitizeFinalPrompt($('#positivePrompt').value);$('#positivePrompt').value=checked.out;if(checked.changes.length)$('#replacementReport').textContent=checked.changes.map(x=>`${x.from} → ${x.to} (${x.count})`).join('\n')}if($('#mode').value==='external')await generateViaExternal();else await generateViaComfy()}catch(e){$('#progress').textContent='Errore: '+e.message;console.error(e)}finally{$('#generate').disabled=false}}
async function generateViaExternal(){const p=activeProvider(),key=LS.get('providers',{})[p];if(!key)return openManual(p,$('#positivePrompt').value);const first=selectedSources()[0],blob=first?(first.map.source==='identity'?first.char.identity:first.char.character):null;$('#progress').textContent=`Generazione con ${p}…`;const out=await generateExternal(p,key,$('#positivePrompt').value,blob,$('#format').value);await saveResult(out,`external-${p}-${Date.now()}.png`);$('#progress').textContent='Generazione completata.'}
async function generateViaComfy(){if(!state.activeWorkflow)throw new Error('Seleziona un workflow.');const c=connection();LS.set('connection',c);const graph=structuredClone(state.activeWorkflow.graph),m=state.activeWorkflow.mapping||{};m.positive?.forEach(x=>setField(graph,x.nodeId,x.field,$('#positivePrompt').value));m.negative?.forEach(x=>setField(graph,x.nodeId,x.field,$('#negativePrompt').value));if(m.seed?.nodeId)setField(graph,m.seed.nodeId,m.seed.field||'seed',Math.floor(Math.random()*2147483647));const fmt=formats[$('#format').value];if(fmt&&m.resolution?.nodeId){setField(graph,m.resolution.nodeId,m.resolution.widthField||'width',fmt[0]);setField(graph,m.resolution.nodeId,m.resolution.heightField||'height',fmt[1])}if(m.frames?.nodeId&&$('#frames').value)setField(graph,m.frames.nodeId,m.frames.field||'length',+$('#frames').value);if(m.fps?.nodeId&&$('#fps').value)setField(graph,m.fps.nodeId,m.fps.field||'frame_rate',+$('#fps').value);const uploads=new Map(),maps=m.images||[],rel=maps.filter(x=>x.source!=='pose');for(const mp of maps){let blob,name;if(mp.source==='pose'){blob=state.poseBlob;name='pose-reference.png'}else{const idx=rel.indexOf(mp),ch=state.characters.find(x=>x.id===state.slots[idx]);blob=mp.source==='identity'?ch?.identity:ch?.character;if(ch)name=fileName(mp.source,ch)}if(!blob||!name)continue;const key=name+'-'+blob.size;if(!uploads.has(key)){await comfy.uploadImage(c,blob,name);uploads.set(key,name)}setField(graph,mp.nodeId,mp.field,name)}const clientId=uid();$('#progress').textContent='Workflow inviato…';const q=await comfy.queue(c,graph,clientId);if(!q.prompt_id)throw new Error('ComfyUI non ha restituito prompt_id.');const h=await comfy.wait(c,q.prompt_id,ms=>$('#progress').textContent=`Generazione in corso… ${Math.floor(ms/1000)} s`);const files=comfy.outputs(h);if(!files.length)throw new Error('ComfyUI ha completato il workflow senza file images/gifs/videos.');for(const f of files){const blob=await comfy.fetchOutput(c,f);await saveResult(blob,f.filename)}$('#progress').textContent=`Completato: ${files.length} file.`}
function setField(g,id,field,val){if(g[id]?.inputs&&field)g[id].inputs[field]=val}
async function saveResult(blob,name){const item={id:uid(),blob,name,type:blob.type,hidden:false,active:true,createdAt:Date.now()};await put('archive',item);state.archive=await all('archive');renderArchive();const u=blobUrl(blob),video=/\.(mp4|webm|mov|gif)$/i.test(name)||blob.type.startsWith('video/');$('#result').classList.toggle('transparent-preview',$('#transparentBackground').checked&&!video);$('#result').innerHTML=video?`<video class="thumb" controls src="${u}"></video>`:`<img class="thumb" src="${u}">`}
function renderArchive(){$('#archiveList').innerHTML=state.archive.sort((a,b)=>b.createdAt-a.createdAt).map(a=>{const u=blobUrl(a.blob),v=/\.(mp4|webm|mov)$/i.test(a.name)||a.type?.startsWith('video/');return`<div class="card">${v?`<video class="thumb ${a.hidden?'blur':''}" controls src="${u}"></video>`:`<img class="thumb ${a.hidden?'blur':''}" src="${u}">`}<b>${escapeHtml(a.name)}</b><label><input data-active-ar="${a.id}" type="checkbox" ${a.active?'checked':''}> Attiva nel progetto</label><div class="card-actions"><button data-down-ar="${a.id}">Scarica</button><button data-hide-ar="${a.id}">👁️</button><button data-del-ar="${a.id}">Elimina</button></div></div>`}).join('')||'<p>Archivio vuoto.</p>';$$('[data-active-ar]').forEach(x=>x.onchange=async()=>{const a=state.archive.find(z=>z.id===x.dataset.activeAr);a.active=x.checked;await put('archive',a)});$$('[data-down-ar]').forEach(b=>b.onclick=()=>{const a=state.archive.find(x=>x.id===b.dataset.downAr);download(a.blob,a.name)});$$('[data-hide-ar]').forEach(b=>b.onclick=async()=>{const a=state.archive.find(x=>x.id===b.dataset.hideAr);a.hidden=!a.hidden;await put('archive',a);renderArchive()});$$('[data-del-ar]').forEach(b=>b.onclick=async()=>{if(confirm('Eliminare?')){await del('archive',b.dataset.delAr);state.archive=await all('archive');renderArchive()}})}
function sceneSnapshot(name){return{id:uid(),name,characterText:$('#characterText').value,sceneText:$('#sceneText').value,negativeExtra:$('#negativeExtra').value,style:$('#style').value,format:$('#format').value,posePreset:$('#posePreset').value,qualities:$$('.quality:checked').map(x=>x.value),lighting:$('#lighting').value,composition:$('#composition').value,frames:$('#frames').value,fps:$('#fps').value,consistency:$('#consistency').checked,safeMode:$('#safeMode').checked,transparentBackground:$('#transparentBackground').checked,sliders:Object.fromEntries(sliderDefs.map(([id])=>[id,$('#'+id).value])),director:state.director.state(),slots:{...state.slots},translated:{...state.translated}}}
function saveScene(){const name=prompt('Nome della scena:');if(!name)return;const s=LS.get('scenes',[]);s.push(sceneSnapshot(name));LS.set('scenes',s);renderSavedScenes()}
function renderSavedScenes(){const s=LS.get('scenes',[]);$('#savedScenes').innerHTML='<option value="">Scene salvate</option>'+s.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('')}
function loadScene(){const s=LS.get('scenes',[]).find(x=>x.id===$('#savedScenes').value);if(!s)return;['characterText','sceneText','negativeExtra','style','format','posePreset','lighting','composition','frames','fps'].forEach(k=>$('#'+k).value=s[k]??'');$('#consistency').checked=s.consistency;$('#safeMode').checked=s.safeMode;$('#transparentBackground').checked=!!s.transparentBackground;$$('.quality').forEach(x=>x.checked=s.qualities.includes(x.value));sliderDefs.forEach(([id])=>{$('#'+id).value=s.sliders[id];$('#'+id).nextElementSibling.value=s.sliders[id]});state.slots=s.slots||{};state.translated=s.translated||{char:'',scene:'',neg:''};state.director.set(s.director);renderSlots();rebuildPrompt()}
function deleteScene(){const id=$('#savedScenes').value;if(!id)return;LS.set('scenes',LS.get('scenes',[]).filter(x=>x.id!==id));renderSavedScenes()}
async function copyImage(blob){try{await navigator.clipboard.write([new ClipboardItem({'image/png':await toPng(blob)})])}catch{alert('Il browser non consente la copia immagine. Usa Scarica.') }}
function toPng(blob){if(blob.type==='image/png')return blob;return new Promise((ok,no)=>{const i=new Image,u=blobUrl(blob);i.onload=()=>{const c=document.createElement('canvas');c.width=i.naturalWidth;c.height=i.naturalHeight;c.getContext('2d').drawImage(i,0,0);c.toBlob(ok,'image/png');URL.revokeObjectURL(u)};i.onerror=no;i.src=u})}
function download(blob,name){const a=document.createElement('a');a.href=blobUrl(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}

async function collectBackup(){return{workflows:await all('workflows'),characters:await all('characters'),archive:await all('archive'),localStorage:Object.fromEntries(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)]))}}
function backupMessage(text,ok=true){const el=$('#backupStatus');if(el){el.textContent=text;el.className='notice compact '+(ok?'success':'error')}}
async function selectBackupFolder(){try{state.backupHandle=await chooseDirectory();backupMessage(`Cartella selezionata: ${state.backupHandle.name}\nIl backup resterà fuori dai dati del browser.`);configureAutoBackup();await backupNow()}catch(e){backupMessage(e.message,false)}}
async function backupNow(){try{const text=await encodeBackup(await collectBackup());if(!state.backupHandle)throw new Error('Prima scegli la cartella Backup Vault, oppure usa Esporta backup.');await writeDirectory(state.backupHandle,text);backupMessage(`Backup salvato: ${new Date().toLocaleString('it-IT')}\nFile: prompt-director-backup.json`)}catch(e){backupMessage(e.message,false)}}
async function exportBackup(){try{const text=await encodeBackup(await collectBackup());downloadText(text,`prompt-director-backup-${new Date().toISOString().slice(0,10)}.json`);backupMessage('Backup esportato. Conserva il file fuori dal browser.')}catch(e){backupMessage(e.message,false)}}
async function importBackup(e){const file=e.target.files?.[0];if(!file)return;try{const data=decodeBackup(await file.text());if(!confirm('Ripristinare il backup? I dati attuali verranno sostituiti.'))return;for(const store of ['workflows','characters','archive']){await clearStore(store);for(const item of data[store]||[])await put(store,item)}localStorage.clear();for(const [k,v] of Object.entries(data.localStorage||{}))localStorage.setItem(k,v);backupMessage('Ripristino completato. Ricarico l’app…');setTimeout(()=>location.reload(),700)}catch(err){backupMessage('Ripristino fallito: '+err.message,false)}finally{e.target.value=''}}
function configureAutoBackup(){clearInterval(state.backupTimer);if($('#autoBackup')?.checked&&state.backupHandle)state.backupTimer=setInterval(backupNow,5*60*1000)}
