export function base(c){return `${c.protocol}://${c.host}${c.port?':'+c.port:''}`}
export function headers(c){if(c.authType==='basic')return{Authorization:'Basic '+btoa(`${c.username}:${c.secret}`)};if(c.authType==='bearer')return{Authorization:'Bearer '+c.secret};return{}}
export async function test(c){const r=await fetch(base(c)+'/system_stats',{headers:headers(c)});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
export function validateWorkflow(j){if(!j||Array.isArray(j)||typeof j!=='object')return'Il file non contiene un oggetto JSON valido.';if(Array.isArray(j.nodes)||Array.isArray(j.links))return'Workflow non in formato API. In ComfyUI usa “Save (API Format)” / abilita Dev Mode e salva il formato API.';const vals=Object.values(j);if(!vals.length||!vals.every(n=>n&&typeof n==='object'&&typeof n.class_type==='string'&&n.inputs&&typeof n.inputs==='object'))return'Formato API non riconosciuto: ogni nodo deve avere class_type e inputs.';return''}
export async function uploadImage(c,blob,name){const f=new FormData();f.append('image',new File([blob],name,{type:blob.type||'image/png'}));f.append('overwrite','true');const r=await fetch(base(c)+'/upload/image',{method:'POST',headers:headers(c),body:f});if(!r.ok)throw new Error('Upload immagine: '+await r.text());return r.json()}
export async function queue(c,graph,clientId){const body=JSON.stringify({prompt:graph,client_id:clientId});const r=await fetch(base(c)+'/prompt',{method:'POST',headers:headers(c),body});if(!r.ok)throw new Error('Invio workflow: '+await r.text());return r.json()}
export async function wait(c,id,onTick,timeout=1200000){const start=Date.now();while(Date.now()-start<timeout){onTick?.(Date.now()-start);const r=await fetch(base(c)+'/history/'+encodeURIComponent(id),{headers:headers(c)});if(r.ok){const j=await r.json();if(j[id])return j[id]}await new Promise(x=>setTimeout(x,1500))}throw new Error('Timeout generazione superato.')}
export function outputs(history){const out=[];Object.values(history.outputs||{}).forEach(node=>['images','gifs','videos'].forEach(k=>(node[k]||[]).forEach(f=>out.push(f))));return out}
export async function fetchOutput(c,f){const q=new URLSearchParams({filename:f.filename,subfolder:f.subfolder||'',type:f.type||'output'});const r=await fetch(base(c)+'/view?'+q,{headers:headers(c)});if(!r.ok)throw new Error('Download risultato fallito');return r.blob()}
export const safeName=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]/g,'').slice(0,40)||'image';
