export class Director{constructor(top,side,zoom,onchange){this.c={top,side,zoom};this.onchange=onchange;this.angle=0;this.radius=.72;this.height=.5;this.zoom=.25;this.drag=null;Object.entries(this.c).forEach(([k,c])=>{c.addEventListener('pointerdown',e=>{this.drag=k;c.setPointerCapture(e.pointerId);this.move(k,e)});c.addEventListener('pointermove',e=>{if(this.drag===k)this.move(k,e)});c.addEventListener('pointerup',()=>this.drag=null)});this.draw()}
move(k,e){const c=this.c[k],r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height;if(k==='top'){const dx=x-c.width/2,dy=y-c.height/2;this.angle=(Math.atan2(dy,dx)*180/Math.PI+360)%360;this.radius=Math.max(.25,Math.min(1,Math.hypot(dx,dy)/(c.width*.42)));this.zoom=1-this.radius}else if(k==='side')this.height=Math.max(0,Math.min(1,1-y/c.height));else this.zoom=Math.max(0,Math.min(1,y/c.height));this.draw();this.onchange?.(this.state())}
state(){return{angle:this.angle,height:this.height,zoom:this.zoom,view:this.view(),heightName:this.heightName(),zoomName:this.zoomName(),tags:[this.viewTag(),this.heightTag(),this.zoomTag()]}}
view(){const a=this.angle;if(a<22.5||a>=337.5)return'frontale';if(a<67.5)return'tre quarti sinistra';if(a<112.5)return'laterale sinistra';if(a<157.5)return'tre quarti posteriore sinistra';if(a<202.5)return'da dietro';if(a<247.5)return'tre quarti posteriore destra';if(a<292.5)return'laterale destra';return'tre quarti destra'}
viewTag(){return({'frontale':'front view','tre quarti sinistra':'three-quarter left view','laterale sinistra':'left side view','tre quarti posteriore sinistra':'rear three-quarter left view','da dietro':'back view','tre quarti posteriore destra':'rear three-quarter right view','laterale destra':'right side view','tre quarti destra':'three-quarter right view'})[this.view()]}
heightName(){return this.height<.33?'dal basso':this.height>.67?'dall’alto':'livello occhi'}heightTag(){return this.height<.33?'low angle shot, looking up at the character':this.height>.67?'high angle shot, looking down at the character':'eye-level shot'}
zoomName(){return this.zoom<.16?'figura intera':this.zoom<.35?'tre quarti':this.zoom<.55?'mezzo busto':this.zoom<.75?'primo piano':'primissimo piano'}zoomTag(){return({'figura intera':'wide shot, full body, head-to-toe fully visible','tre quarti':'medium shot, three-quarter body, full head visible','mezzo busto':'medium close-up shot, upper body, full head visible with headroom','primo piano':'close-up portrait, detailed face, full head visible with headroom','primissimo piano':'extreme close-up, detailed face, full head visible, not cropped'})[this.zoomName()]}
set(s){Object.assign(this,s||{});this.draw()}draw(){this.drawTop();this.drawSide();this.drawZoom()}
arrow(x,cx,cy,angle=0,len=42){x.save();x.translate(cx,cy);x.rotate(angle);x.strokeStyle='#39ff75';x.fillStyle='#39ff75';x.lineWidth=5;x.beginPath();x.moveTo(0,0);x.lineTo(len,0);x.stroke();x.beginPath();x.moveTo(len,0);x.lineTo(len-13,-9);x.lineTo(len-13,9);x.closePath();x.fill();x.restore()}
drawTop(){const c=this.c.top,x=c.getContext('2d'),cx=c.width/2,cy=c.height/2,R=c.width*.38;x.clearRect(0,0,c.width,c.height);x.strokeStyle='#42617f';x.lineWidth=2;x.beginPath();x.arc(cx,cy,R,0,7);x.stroke();x.fillStyle='#b8c9df';x.beginPath();x.arc(cx,cy,20,0,7);x.fill();this.arrow(x,cx,cy,0,48);x.fillStyle='#39ff75';x.font='bold 12px sans-serif';x.fillText('SGUARDO',cx+28,cy-12);const r=R*this.radius,a=this.angle*Math.PI/180,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;x.strokeStyle='#39d98a';x.beginPath();x.moveTo(px,py);x.lineTo(cx,cy);x.stroke();x.fillStyle='#55a7ff';x.fillRect(px-12,py-9,24,18)}
drawSide(){const c=this.c.side,x=c.getContext('2d'),y=c.height*(1-this.height);x.clearRect(0,0,c.width,c.height);x.strokeStyle='#42617f';x.beginPath();x.moveTo(40,c.height-35);x.lineTo(c.width-30,c.height-35);x.stroke();x.fillStyle='#b8c9df';x.fillRect(c.width/2-8,75,16,150);x.beginPath();x.arc(c.width/2,62,18,0,7);x.fill();this.arrow(x,c.width/2+4,62,0,42);x.fillStyle='#55a7ff';x.fillRect(40,y-10,30,20);x.strokeStyle='#39d98a';x.beginPath();x.moveTo(70,y);x.lineTo(c.width/2,140);x.stroke()}
drawZoom(){const c=this.c.zoom,x=c.getContext('2d'),y=c.height*this.zoom;x.clearRect(0,0,c.width,c.height);x.fillStyle='#b8c9df';x.beginPath();x.arc(c.width/2,45,25,0,7);x.fill();x.fillRect(c.width/2-28,70,56,155);this.arrow(x,c.width/2+5,45,0,48);x.strokeStyle='#39d98a';x.lineWidth=4;x.beginPath();x.moveTo(30,y);x.lineTo(c.width-30,y);x.stroke()}}
