const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
const DEFAULT_EXCLUDED_IDS = new Set(['host','port','username','secret','protocol','authType','frames','fps']);
function isWritableTextField(el){if(!(el instanceof HTMLTextAreaElement||el instanceof HTMLInputElement)||el.disabled||el.readOnly||el.dataset.noSpeech==='true'||DEFAULT_EXCLUDED_IDS.has(el.id))return false;if(el instanceof HTMLInputElement){const t=(el.type||'text').toLowerCase();if(!['text','search'].includes(t)||el.closest('#mappingEditor')||el.matches('[data-key]'))return false}return true}
function punctuation(t,l){if(!/^it/i.test(l))return t;return t.replace(/\bpunto e virgola\b/gi,';').replace(/\bpunto interrogativo\b/gi,'?').replace(/\bpunto esclamativo\b/gi,'!').replace(/\bdue punti\b/gi,':').replace(/\bvirgola\b/gi,',').replace(/\b(?:a capo|nuova riga)\b/gi,'\n').replace(/\bpunto\b/gi,'.')}
function norm(s){return String(s||'').toLocaleLowerCase().replace(/[\s\u00a0]+/g,' ').replace(/^[\s,.;:!?]+|[\s,.;:!?]+$/g,'').trim()}
function removeAdjacentDuplicates(text){const words=text.trim().split(/\s+/),out=[];for(const w of words){if(!out.length||norm(out[out.length-1])!==norm(w))out.push(w)}let s=out.join(' ');const parts=s.split(/(?<=[.!?])\s+/);return parts.filter((p,i,a)=>i===0||norm(p)!==norm(a[i-1])).join(' ')}
function removeOverlap(existing,incoming){const a=existing.trim().split(/\s+/),b=incoming.trim().split(/\s+/);for(let n=Math.min(20,a.length,b.length);n>0;n--){if(norm(a.slice(-n).join(' '))===norm(b.slice(0,n).join(' ')))return b.slice(n).join(' ')}return incoming}
function insert(field,text){text=removeAdjacentDuplicates(removeOverlap(field.value,text));if(!text.trim())return false;const st=Number.isInteger(field.selectionStart)?field.selectionStart:field.value.length,en=Number.isInteger(field.selectionEnd)?field.selectionEnd:st,before=field.value.slice(0,st),after=field.value.slice(en),space=before&&!/[\s\n]$/.test(before)&&!/^[,.;:!?]/.test(text)?' ':'';const value=space+text;field.value=before+value+after;const c=before.length+value.length;field.setSelectionRange?.(c,c);field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new Event('change',{bubbles:true}));field.focus();return true}
function status(w,m,k=''){const e=w.querySelector('.voice-status');if(e){e.textContent=m;e.className=`voice-status ${k}`.trim()}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
export function initSpeechInputs({languageSelect=null}={}){let active=null;const lang=()=>languageSelect?.value||localStorage.getItem('pdSpeechLanguage')||'it-IT';function stop(){try{active?.recognition.stop()}catch{}}function enhance(field){if(!isWritableTextField(field)||field.dataset.speechReady==='true')return;field.dataset.speechReady='true';const w=document.createElement('div');w.className='voice-field';field.parentNode.insertBefore(w,field);w.appendChild(field);w.insertAdjacentHTML('beforeend',`<div class="voice-toolbar"><button type="button" class="voice-mic" title="Avvia dettatura">🎤 <span>Detta</span></button><button type="button" class="voice-stop" disabled>⏹</button><span class="voice-status" aria-live="polite">Pronto</span></div>`);const mic=w.querySelector('.voice-mic'),btnStop=w.querySelector('.voice-stop');if(!SpeechRecognition){mic.disabled=true;status(w,'Dettatura non supportata','error');return}mic.onclick=()=>{if(active?.field===field){stop();return}stop();const r=new SpeechRecognition();r.lang=lang();r.continuous=true;r.interimResults=false;r.maxAlternatives=1;let last='',lastAt=0;active={recognition:r,field,wrapper:w};mic.classList.add('listening');mic.querySelector('span').textContent='Ascolto…';btnStop.disabled=false;status(w,`In ascolto (${r.lang})…`,'listening');r.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){const result=e.results[i];if(!result.isFinal)continue;let text=removeAdjacentDuplicates(punctuation((result[0]?.transcript||'').trim(),r.lang));const key=norm(text),now=Date.now();if(!key||(key===last&&now-lastAt<15000))continue;last=key;lastAt=now;if(insert(field,text))status(w,'Inserito senza doppioni. Continuo ad ascoltare…','listening')}};r.onerror=e=>status(w,({'not-allowed':'Permesso microfono negato','no-speech':'Nessuna voce rilevata','audio-capture':'Microfono non disponibile','network':'Errore servizio vocale'})[e.error]||`Errore: ${e.error}`,'error');r.onend=()=>{mic.classList.remove('listening');mic.querySelector('span').textContent='Detta';btnStop.disabled=true;if(active?.recognition===r)active=null;if(!w.querySelector('.voice-status.error'))status(w,'Dettatura terminata')};try{r.start()}catch(e){status(w,e.message,'error')}};btnStop.onclick=stop}
function scan(root=document){root.querySelectorAll?.('textarea,input').forEach(enhance)}scan();new MutationObserver(rs=>rs.forEach(r=>r.addedNodes.forEach(n=>{if(n.nodeType===1){if(n.matches?.('textarea,input'))enhance(n);scan(n)}}))).observe(document.body,{childList:true,subtree:true});languageSelect?.addEventListener('change',()=>localStorage.setItem('pdSpeechLanguage',languageSelect.value));document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});return{stop,supported:!!SpeechRecognition}}
